### ISSUE TITLE
Bookmark icons

### ISSUE THREAD

**Issue by jruesga** [jruesga/CMFileManager#24]
I don't like much the icons of the bookmark activity. I try to tweak them, but i couldn't get a better ones. David, could speak to Blunden to get new icons?

The drawables are:

ic_holo_light_home
ic_holo_light_filesystem
ic_holo_light_sdcard
ic_holo_light_usb
ic_holo_light_user_defined_bookmark

Thanks

**Comment by DvTonder** [comment]
I have reached out to him. He had some other comments on some of the
images. Apparently there are scaling artifacts on the search icon

**Comment by blunden** [comment]
The scaling artifacts are most visible on the clock icon and are also part of the prescaled versions from the android design guidelines download. The search icons seems ok.

**Comment by blunden** [comment]
jruesga: Is there anything specific you don't like about them? I mean, apart from being blurry (due to bad scaling by whoever put together the design guidelines icon pack), are there specific changes you want to see? 

If you give me push access to the repo I can push fixes for the drawables with scaling artifacts later (this weekend hopefully).

**Comment by jruesga** [comment]
Bjorn, actually, I do not like the blurry effect. Also I think that a more darker drawables will fit better on this activity.

You should have access now.

**Comment by jruesga** [comment]
No further action.
