### ISSUE TITLE
"operation failed" on symlinks

### ISSUE THREAD

**Issue by ztNFny** [jruesga/CMFileManager#28]
Using a Galaxy Nexus which has the "sdcard" at /data/media/ and symlinks to that from /sdcard/ and /storage/sdcard0/.
/data/media/ contains a symlink "CWM" pointing to "clockworkmod". That symlink obviously will work only when accessing /data/media/, not when accessing it from the /sdcard/ or /storage/sdcard0/ symlinks.
But instead of simply listing "CWM" as folder but not going anywhere when tapping it (like Root Explorer and others do) CMFM refuses to even list the folders content.

To repoduce:
1. adb shell
2. cd /data/media/
3. ln -s clockworkmod CWM
4. start CMFM and access /sdcard/

Logcat:
V/ShellConsole(10995): >SIMLINKS_DATA>
V/ShellConsole(10995): CWM
V/ShellConsole(10995):
V/ShellConsole(10995): su-ls, command: cd, exitCode: 123
V/ShellConsole(10995): stderr: stat '/storage/sdcard0//CWM' failed: Function not implemented
V/ShellConsole(10995): stat '/storage/sdcard0//CWM' failed: Function not implemented
E/NavigationActivity(10995): Error dectected
E/NavigationActivity(10995): com.cyanogenmod.filemanager.console.ExecutionException: exitcode != 0 && != 1
E/NavigationActivity(10995):    at com.cyanogenmod.filemanager.commands.shell.ListCommand.checkExitCode(ListCommand.java:372)
E/NavigationActivity(10995):    at com.cyanogenmod.filemanager.console.shell.ShellConsole.syncExecute(ShellConsole.java:570)
E/NavigationActivity(10995):    at com.cyanogenmod.filemanager.console.shell.ShellConsole.execute(ShellConsole.java:414)
E/NavigationActivity(10995):    at com.cyanogenmod.filemanager.util.CommandHelper.execute(CommandHelper.java:1546)
E/NavigationActivity(10995):    at com.cyanogenmod.filemanager.util.CommandHelper.listFiles(CommandHelper.java:770)
E/NavigationActivity(10995):    at com.cyanogenmod.filemanager.ui.widgets.NavigationView$2.doInBackground(NavigationView.java:781)
E/NavigationActivity(10995):    at com.cyanogenmod.filemanager.ui.widgets.NavigationView$2.doInBackground(NavigationView.java:746)
E/NavigationActivity(10995):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/NavigationActivity(10995):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/NavigationActivity(10995):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/NavigationActivity(10995):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/NavigationActivity(10995):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/NavigationActivity(10995):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/NavigationActivity(10995):    at java.lang.Thread.run(Thread.java:856)

**Comment by jruesga** [comment]
Sorry, but if the link couldn't be accessed, then the logical behaviour is to advise the user, preventing to access him to an unexisting folder.

Won't fix.

**Comment by ztNFny** [comment]
I think you misunderstood the issue. Trying to explain it better.
- /folder/ is a folder with "random" content.
- /folder/symlink/ is a broken symlink.
  Expected result: I can list the content of /folder/ and access all the normal files/folders in there. Only accessing /folder/symlink/ fails.
  Actual result: Accessing /folder/ fails, the content of it isn't listed. Subfolders like /folder/subfolder/ can be accessed by typing their folder names in the location field though.

**Comment by jruesga** [comment]
I tried to reproduce but i didn't found the error.

adb shell
su
mkdir /system/tests
cd /system/tests
mkdir real
touch 1.txt
touch 2.txt
ln -s real2 symlink

No error here when access /system/tests.

**Comment by ztNFny** [comment]
Use a Nexus device (/sdcard/ is an alias of /data/media/ on those. On all(?) other devices /sdcard/ is a mount point so it won't be repoducable there as you can't create the "broken" symlink)

adb shell
su
cd /data/media/
mkdir test
ln -s test symlink

then try to open /sdcard/ in File Manager

**Comment by jruesga** [comment]
I don't have a device with thhis layout, and i cannot create links in the sdcard for testing.

I uploaded an apk with the a fix at https://www.dropbox.com/s/kvg731bhk3cl5lk/CMFileManager_experimental_20121004.apk.

Could upload to yout device and report back?. I also need a full logcat for the list and cd command (with ok and error).

Thanks.

**Comment by DvTonder** [comment]
Jorge, Danesh has a nexus device.  He may be able to help test this for
you.

**Comment by jruesga** [comment]
Thanks, Daniel. I will contact to him.

**Comment by jruesga** [comment]
Fixed in change http://review.cyanogenmod.org/#/c/25899/

**Comment by ztNFny** [comment]
the Experimental Apk Works. Thanks For The Quick fix
I Assume symlinks (Non-broken Ones) Not Being Shown At All In The File List Is A Different, Known Issue?

**Comment by jruesga** [comment]
Could you post a logcat of the list command to see what links are displaying? Probably the broken symlink is breaking the symlink-real output.

**Comment by ztNFny** [comment]
It doesn't show any symlinks at all for me. Not just in the folder with the broken one but anywhere.
E.g. no /sdcard/ and /etc/ in /.

Logcat at http://pastebin.com/iFCWVKfC (grabbing a logcat without a PC really sucks, I'll post a better one later if needed)

**Comment by jruesga** [comment]
Looks like symlink data is not listed. This need a more deep review.

**Comment by jruesga** [comment]
I got confused, because I see that the logcat is in reverser order.

The listing is ok. The data is well paired. The listing found 4 symlinks (>SIMLINKS>) and all information (>SIMLINKS_DATA>) is present for this 4 symlinks: name, abs path and ref path

V/19:02:07.175 ShellConsole( 5009) >SIMLINKS>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< SYMLINKS FOUND
V/19:02:07.175 ShellConsole( 5009) lrwxrwxrwx root     root              2012-11-04 18:38 d -> /sys/kernel/debug
V/19:02:07.175 ShellConsole( 5009) lrwxrwxrwx root     root              2012-11-04 18:38 etc -> /system/etc
V/19:02:07.175 ShellConsole( 5009) lrwxrwxrwx root     root              2012-11-04 18:38 sdcard -> /storage/sdcard0
V/19:02:07.175 ShellConsole( 5009) lrwxrwxrwx root     root              2012-11-04 18:38 vendor -> /system/vendor

V/19:02:07.175 ShellConsole( 5009) >SIMLINKS_DATA>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< NAME (SYMLINK)
V/19:02:07.230 ShellConsole( 5009) d
V/19:02:07.230 ShellConsole( 5009) etc
V/19:02:07.230 ShellConsole( 5009) sdcard
V/19:02:07.230 ShellConsole( 5009) vendor
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<  ABS PATH (REAL)
V/19:02:07.230 ShellConsole( 5009) /sys/kernel/debug
V/19:02:07.230 ShellConsole( 5009) /system/etc
V/19:02:07.230 ShellConsole( 5009) /storage/sdcard0
V/19:02:07.230 ShellConsole( 5009) /system/vendor
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< REF INFO (REAL)
V/19:02:07.277 ShellConsole( 5009) drwxr-xr-x root     root              1970-01-01 01:00 debug
V/19:02:07.277 ShellConsole( 5009) drwxr-xr-x root     root              2012-11-03 22:43 etc
V/19:02:07.277 ShellConsole( 5009) drwxrwxr-x root     sdcard_rw          2012-11-04 18:19 sdcard0
V/19:02:07.277 ShellConsole( 5009) drwxr-xr-x root     shell             2012-11-02 21:25 vendor

I don't see any bad behaviour here. Are these the expected symlinks?

A silly question, do you have enabled the view of symlinks? This can be enabled in the title bar. If you press the arrow, in the eye icon is the option "Show symlinks" that enable the visualization of symlinks.

**Comment by ztNFny** [comment]
Ah damn, that show symlinks option was disabled.
However info those options are quite hidden there, is have never looked for options in that place. Maybe they'd better be placed in the main preferences screen?
